### Request access token

POST http://localhost:3001/auth/token
Content-Type: application/json

{
"password" : "admin"
}

### Verify access token

GET http://localhost:3001/auth/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Mzc3MWRlYTkwYTc4NjllNzdjMTc.z8ZJjS4aSbhn6NnoW65WIWZWRzxxVUsIUEzwInvHnew
