# TODO: Update package locations using `/packages` dir
version: '3'
services:
  client:
    container_name: client
    env_file: .env
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      args:
        VITE_API_HOST: ${VITE_API_HOST}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '${CLIENT_PORT}:80'
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    env_file: '.env'
    networks:
      - app-network
    volumes:
      - ./packages/api/data/production.sqlite:/api/data/production.sqlite
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
