version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file: '.env'
    networks:
      - app-network
    volumes:
      - ./api/data/production.sqlite:/api/data/production.sqlite
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
