version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=http://api:3001
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network
    volumes:
      - ./api/data/production.sqlite:/api/data/production.sqlite
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
